[package]
name = "day17_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
input_helpers = { version = "0.1.0", path = "../../../2020/input_helpers" }
simple_grid = { version = "0.1.0", path = "../../../helpers/rs/simple_grid" }
